version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc12345
      POSTGRES_DB: fullstack-nextjs